sudo: false

cache:
  yarn: true
  directories:
    - "node_modules"

language: node_js

env:
  global:
    - NODE_VERSION=stable

matrix:
  include:
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@latest
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@latest
    - node_js: 12
      env: REACT_NATIVE_VERSION=react-native@latest
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@next
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@next
    - node_js: 12
      env: REACT_NATIVE_VERSION=react-native@next

    # Previous react-native versions
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@0.60.0
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@0.60.0
    - node_js: 12
      env: REACT_NATIVE_VERSION=react-native@0.60.0
  fast_finish: true


install:


before_script:
  - export TEMPLATE_PATH="$(pwd)"
  - cd ..
  - npx react-native init TestApp --template=$TEMPLATE_PATH && cd TestApp

script:
  - cat package.json
  - yarn codequality
  - npx react-native run-ios
