sudo: false

cache:
  yarn: true
  directories:
    - "node_modules"

language: node_js

env:
  global:
    - NODE_VERSION=stable

matrix:
  include:
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@latest
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@latest
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@next
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@next
    # Previous react-native versions
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@0.59.0
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@0.59.0
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@0.59.1
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@0.59.1
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@0.59.2
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@0.59.2
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@0.59.3
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@0.59.3
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@0.59.4
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@0.59.4
  fast_finish: true


install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

  - yarn global add react-native-cli

before_script:
  - react-native init TestApp --template tuil --version $REACT_NATIVE_VERSION && cd TestApp

script:
  - cat package.json
  - yarn lint
