language: node_js

cache:
  yarn: true
  directories:
    - "node_modules"

node_js:
  - 10
  - 11

sudo: false

before_script:
  - yarn global add react-native-cli

script:
 — react-native init TestApp --template tuil && cd TestApp && node setup.js
