sudo: false

cache:
  yarn: true
  directories:
    - "node_modules"

language: node_js

env:
  global:
    - NODE_VERSION=stable

matrix:
  include:
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@latest
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@latest
    - node_js: 12
      env: REACT_NATIVE_VERSION=react-native@latest
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@next
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@next
    - node_js: 12
      env: REACT_NATIVE_VERSION=react-native@next

    # Previous react-native versions
    - node_js: 10
      env: REACT_NATIVE_VERSION=react-native@0.60.0
    - node_js: 11
      env: REACT_NATIVE_VERSION=react-native@0.60.0
    - node_js: 12
      env: REACT_NATIVE_VERSION=react-native@0.60.0
  fast_finish: true


install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

  # - yarn global add react-native-cli

before_script:
  - cd ..
  - npx react-native init TestApp --template=/home/travis/build/patrickkempff/react-native-template-tuil
  # - npx react-native init TestApp --template=tuil
  # - react-native init TestApp --template tuil --version $REACT_NATIVE_VERSION && cd TestApp

script:
  - cat package.json
  - yarn lint
