language: node_js

cache:
  yarn: true
  directories:
    - "node_modules"

node_js:
  - 10
  - 11

sudo: false

install:
  - yarn global add react-native-cli

before_script:
  - react-native init TestApp --template tuil && cd TestApp

script:
  - cat package.json
  - node setup.js

after_script:
  - yarn test
  - yarn lint
